laboratory 4, Akhmarov Ruslan
itmo-mla/fall-24 pull request #90
Opened 2024-12-24 12:15 UTC by Nolasar

2025-01-09 13:58 UTC, ADmangarakov requested changes

2025-01-09 13:58 UTC, ADmangarakov commented on students/rt-akhmarov/lab_4/dataset/citrus.csv
Датасетов не должно быть

2025-01-09 14:27 UTC, Nolasar commented on students/rt-akhmarov/lab_4/dataset/citrus.csv
Исправил

2025-01-14 19:01 UTC, ADmangarakov approved these changes

2025-01-14 19:01 UTC, merged